Galaxy tool bulk import
research-software-ecosystem/utils pull request #12
Opened 2024-04-29 10:17 UTC by arash77

This pull request adds a GitHub action for bulk importing galaxy tools from https://github.com/galaxyproject/galaxy_tool_metadata_extractor.

2024-04-29 10:30 UTC, paulzierep commented
Thank you very much @arash77 !
We got some questions concerning the import logic:

* We are using the bio.tools ID to match the entries in the galaxy metadata to the RSEc metadata. What should we do with entries without bio.tools ID ? Leave out ? Use the tools name / ID ?
* If there is a tool in the Galaxy metadata list that has a bio.tools ID that does not match with the folders in the RSEc metadata, should we add the folder ? 

This is an example of an entry that is added:
```

{
    "Conda id": "abricate",
    "Conda version": "1.0.1",
    "Description": "Mass screening of contigs for antiobiotic resistance genes",
    "EDAM operation": "Antimicrobial resistance prediction",
    "EDAM topic": "Genomics, Microbiology",
    "Galaxy tool ids": "abricate, abricate_list, abricate_summary",
    "Galaxy wrapper id": "abricate",
    "Galaxy wrapper owner": "iuc",
    "Galaxy wrapper parsed folder": "https://github.com/galaxyproject/tools-iuc/tree/main/tools/abricate",
    "Galaxy wrapper source": "https://github.com/galaxyproject/tools-iuc/tree/master/tools/abricate/",
    "Galaxy wrapper version": "1.0.1",
    "No. of tool users (2022-2023) (usegalaxy.eu)": 1764,
    "Source": "https://github.com/tseemann/abricate",
    "Status": "Up-to-date",
    "ToolShed categories": "Sequence Analysis",
    "ToolShed id": "abricate",
    "Total tool usage (usegalaxy.eu)": 496717,
    "bio.tool description": "Mass screening of contigs for antimicrobial resistance or virulence genes.",
    "bio.tool id": "ABRicate",
    "bio.tool ids": "ABRicate",
    "bio.tool name": "ABRicate",
    "https://usegalaxy.eu": "(3/3)",
    "https://usegalaxy.fr": "(3/3)",
    "https://usegalaxy.org": "(3/3)",
    "https://usegalaxy.org.au": "(3/3)"
}
```
-> this is highly WIP so the entry will still change a lot over the next months, that's ok ?
Any metadata we should not port here ? 

@hmenager @bgruening @matuskalas what do you think ?

2024-04-29 13:00 UTC, bgruening commented
> If there is a tool in the Galaxy metadata list that has a bio.tools ID that does not match with the folders in the RSEc metadata, should we add the folder ?

No, those cases are "interesting" and we should find out why they are not matching. E.g. is Galaxy wrongly annotated? Is the folder here missing?

> We are using the bio.tools ID to match the entries in the galaxy metadata to the RSEc metadata. What should we do with entries without bio.tools ID ? Leave out ? Use the tools name / ID ?

I'm not sure if the Galaxy tool name (what is that?) is a good choice. Ideally, it will be something like the conda package name (assuming this more the upstream name).

2024-04-30 08:02 UTC, paulzierep commented
> I'm not sure if the Galaxy tool name (what is that?) is a good choice. Ideally, it will be something like the conda package name (assuming this more the upstream name).

We could check if the conda id does match with the Galaxy wrapper id (to avoid python / wget / R) conda ids, and only take the conda id for those cases.

2024-04-30 08:04 UTC, paulzierep commented on galaxytool-import/galaxytool-import.py
> +        if not os.path.isdir(directory):
```suggestion
        if not os.path.isdir(directory):
            print(f"No folder found for tool with bio.tool id: {tool_id}")
```

2024-04-30 08:40 UTC, arash77 commented on galaxytool-import/galaxytool-import.py
> +        if not os.path.isdir(directory):
Yes, there wasn't any tool without a folder:
https://github.com/arash77/research-software-ecosystem-content/actions/runs/8891824216/job/24414583117

2024-05-08 07:33 UTC, paulzierep commented
Adding the bulk import also to the content repository: https://github.com/research-software-ecosystem/content/pull/656

2024-05-08 08:02 UTC, paulzierep commented
@arash77 we decided to store all tool JSON that do not yet have a corresponding folder in the content/data dir in a dedicated galaxy-tools folder in this location: https://github.com/research-software-ecosystem/content/tree/master/datasets
Can you add this to the CI ?

2024-05-15 07:11 UTC, hmenager commented
Thanks to all of you for this great work! There are multiple potential explanations to a Galaxy tool missing a bio.tools ID. I can think of a Galaxy annotation problem, or the actual tool not being in bio.tools. I would propose the following:
- import everything (with or without bio.tools IDs) to a dedicated folder. I initially suggested `datasets/galaxy`, but I would rather go somewhere else, as "datasets" has been historically used for many "test imports" and it remains pretty much uncontrolled. so, maybe `imports/galaxy`?
- then move, or copy tools with a bio.tools ID to the "consolidated" `data` folder.
I agree with @bgruening that we should not try to "guess" bio.tools IDs at this stage (we've done it for other sources, and it was a mistake). I'd rather be interested in listing all the Galaxy tools with no bio.tools IDs and feed the information back to bio.tools and Galaxy teams so that the bio.tools entries can be created and the Galaxy tools can be linked at the source.

2024-05-21 16:07 UTC, hmenager commented
Thank you for the modifications @arash77 ! Would you be able to import everything to `imports/galaxy`? It would make it easier to count the amount of entries for Galaxy. Plus, eventually, we would adopt this for all "import sources" (bioconda, debian med, biii, etc.).

2024-05-21 16:53 UTC, arash77 commented
Now, it will import all the tools into `imports/galaxy` and copy those with `bio.tools IDs` into the `data `folder, if the tool folder exists.

2024-05-21 19:17 UTC, hmenager requested changes
There's only one bit I'd like to discuss, which is the path to the files which are reformatted (see review details).

2024-05-21 19:17 UTC, hmenager commented on galaxytool-import/action.yml
> +        FILES='data/*/*.galaxy.json'
Because json files are both in imports/galaxy/*.galaxy.json and data/*/*.galaxy.json, I suggest modifying this mask to */*/*.galaxy.json.

2024-05-21 19:19 UTC, hmenager commented on galaxytool-import/action.yml
> +        FILES='data/*/*.galaxy.json'
Or doing both `data/*/*.galaxy.json` and `imports/galaxy/*.galaxy.json`. your choice!

2024-05-27 07:32 UTC, hmenager approved these changes

2024-05-27 07:32 UTC, merged